// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AskQuestionData,
  AskQuestionErrors,
  AskQuestionResponses,
  GetDocumentData,
  GetDocumentErrors,
  GetDocumentImageData,
  GetDocumentImageErrors,
  GetDocumentImageResponses,
  GetDocumentPageImageData,
  GetDocumentPageImageErrors,
  GetDocumentPageImageResponses,
  GetDocumentResponses,
  GetJobData,
  GetJobErrors,
  GetJobResponses,
  ListDocumentElementsData,
  ListDocumentElementsErrors,
  ListDocumentElementsResponses,
  ListDocumentsData,
  ListDocumentsErrors,
  ListDocumentsResponses,
  LivenessData,
  LivenessResponses,
  ReadinessData,
  ReadinessErrors,
  ReadinessResponses,
  UploadDocumentData,
  UploadDocumentErrors,
  UploadDocumentResponses,
} from "./types.gen";
import {
  zAskQuestionResponse,
  zGetDocumentImageResponse,
  zGetDocumentPageImageResponse,
  zGetDocumentResponse,
  zGetJobResponse,
  zListDocumentElementsResponse,
  zListDocumentsResponse,
  zLivenessResponse,
  zUploadDocumentResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness
 *
 * The process is running.
 */
export const liveness = <ThrowOnError extends boolean = false>(
  options?: Options<LivenessData, ThrowOnError>,
): RequestResult<LivenessResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<LivenessResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await zLivenessResponse.parseAsync(data),
    url: "/health/live",
    ...options,
  });

/**
 * Readiness
 *
 * Dependencies (database, blob storage) are reachable.
 */
export const readiness = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessData, ThrowOnError>,
): RequestResult<ReadinessResponses, ReadinessErrors, ThrowOnError> =>
  (options?.client ?? client).get<ReadinessResponses, ReadinessErrors, ThrowOnError>({
    url: "/health/ready",
    ...options,
  });

/**
 * List Documents
 *
 * Known documents with their latest job status, newest first.
 */
export const listDocuments = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocumentsData, ThrowOnError>,
): RequestResult<ListDocumentsResponses, ListDocumentsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListDocumentsResponses,
    ListDocumentsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zListDocumentsResponse.parseAsync(data),
    url: "/api/v1/documents",
    ...options,
  });

/**
 * Upload Document
 *
 * Stores the file, registers the document by the SHA-256 of its bytes and enqueues an ingestion job. Answers 202 while the job is pending or processing, and 200 when identical content already completed.
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocumentData, ThrowOnError>,
): RequestResult<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadDocumentResponses,
    UploadDocumentErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseValidator: async (data) => await zUploadDocumentResponse.parseAsync(data),
    url: "/api/v1/documents",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Get Job
 *
 * State, stage and page progress of an ingestion job.
 */
export const getJob = <ThrowOnError extends boolean = false>(
  options: Options<GetJobData, ThrowOnError>,
): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> =>
  (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetJobResponse.parseAsync(data),
    url: "/api/v1/jobs/{job_id}",
    ...options,
  });

/**
 * Get Document
 *
 * A document and its latest job.
 */
export const getDocument = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentData, ThrowOnError>,
): RequestResult<GetDocumentResponses, GetDocumentErrors, ThrowOnError> =>
  (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>(
    {
      responseValidator: async (data) => await zGetDocumentResponse.parseAsync(data),
      url: "/api/v1/documents/{document_id}",
      ...options,
    },
  );

/**
 * List Document Elements
 *
 * Captured elements of a completed document, in reading order.
 */
export const listDocumentElements = <ThrowOnError extends boolean = false>(
  options: Options<ListDocumentElementsData, ThrowOnError>,
): RequestResult<
  ListDocumentElementsResponses,
  ListDocumentElementsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListDocumentElementsResponses,
    ListDocumentElementsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zListDocumentElementsResponse.parseAsync(data),
    url: "/api/v1/documents/{document_id}/elements",
    ...options,
  });

/**
 * Get Document Image
 *
 * Stored crop of an image element.
 */
export const getDocumentImage = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentImageData, ThrowOnError>,
): RequestResult<GetDocumentImageResponses, GetDocumentImageErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetDocumentImageResponses,
    GetDocumentImageErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zGetDocumentImageResponse.parseAsync(data),
    url: "/api/v1/documents/{document_id}/images/{element_id}",
    ...options,
  });

/**
 * Get Document Page Image
 *
 * PNG of a whole page at 144 dpi, stored when the document was ingested. Available once the document's latest job has completed.
 */
export const getDocumentPageImage = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentPageImageData, ThrowOnError>,
): RequestResult<
  GetDocumentPageImageResponses,
  GetDocumentPageImageErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDocumentPageImageResponses,
    GetDocumentPageImageErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zGetDocumentPageImageResponse.parseAsync(data),
    url: "/api/v1/documents/{document_id}/pages/{page_number}/image",
    ...options,
  });

/**
 * Ask Question
 *
 * Searches the completed documents by meaning and by exact keywords, asks the local answer model when relevant content exists, and returns the answer with numbered citations. When the documents do not support an answer, status is not_enough_information and no citation or image is returned. The request is cancelled when the client disconnects.
 */
export const askQuestion = <ThrowOnError extends boolean = false>(
  options: Options<AskQuestionData, ThrowOnError>,
): RequestResult<AskQuestionResponses, AskQuestionErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AskQuestionResponses,
    AskQuestionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zAskQuestionResponse.parseAsync(data),
    url: "/api/v1/questions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
