// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnswerBody
 *
 * The answer to a question.
 *
 * Attributes:
 * status: ``answered`` or ``not_enough_information``.
 * reason: Why there is no answer, only when not answered.
 * answer: Markdown with ``[n]`` markers, or the not-enough message.
 * not_covered: What the documents do not answer, for a partial answer.
 * citations: Numbered citations.
 * sources: Every unit supplied to the answer model, in rank order.
 * primary_image: The figure closest to the most relevant cited text.
 * related_images: Other figures of the cited units.
 */
export type AnswerBody = {
    status: AnswerStatus;
    reason: NotEnoughReason | null;
    /**
     * Answer
     */
    answer: string;
    /**
     * Not Covered
     */
    not_covered: string | null;
    /**
     * Citations
     */
    citations: Array<CitationBody>;
    /**
     * Sources
     */
    sources: Array<SourceBody>;
    primary_image: AnswerImageBody | null;
    /**
     * Related Images
     */
    related_images: Array<AnswerImageBody>;
};

/**
 * AnswerImageBody
 *
 * A figure returned with an answer.
 *
 * Attributes:
 * element_id: Image element id.
 * document_id: Document of the figure.
 * document_name: File name of that document.
 * page: Page of the figure.
 * bbox: Position of the figure on the page.
 * caption: Caption of the figure, if any.
 * unit_id: Cited unit that brought the figure.
 * url: Path of the PNG, served by the document image route.
 */
export type AnswerImageBody = {
    /**
     * Element Id
     */
    element_id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Name
     */
    document_name: string;
    /**
     * Page
     */
    page: number;
    bbox: BoundingBoxBody;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Unit Id
     */
    unit_id: string;
    /**
     * Url
     */
    url: string;
};

/**
 * AnswerStatus
 *
 * Whether the documents supported an answer.
 */
export type AnswerStatus = 'answered' | 'not_enough_information';

/**
 * Body_uploadDocument
 */
export type BodyUploadDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BoundingBoxBody
 *
 * Position on a page in PDF points with a top-left origin.
 *
 * Attributes:
 * left: Distance from the left edge of the page.
 * top: Distance from the top edge of the page.
 * right: Distance from the left edge to the right side of the box.
 * bottom: Distance from the top edge to the bottom side of the box.
 * origin: Always ``top_left``.
 */
export type BoundingBoxBody = {
    /**
     * Left
     */
    left: number;
    /**
     * Top
     */
    top: number;
    /**
     * Right
     */
    right: number;
    /**
     * Bottom
     */
    bottom: number;
    /**
     * Origin
     */
    origin?: 'top_left';
};

/**
 * CitationBody
 *
 * A numbered citation of the answer.
 *
 * Attributes:
 * number: Number of the ``[n]`` markers that refer to it.
 * document_id: Cited document.
 * document_name: File name of the cited document.
 * pages: Cited pages, ascending.
 * unit_ids: Retrieval units behind the citation.
 */
export type CitationBody = {
    /**
     * Number
     */
    number: number;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Name
     */
    document_name: string;
    /**
     * Pages
     */
    pages: Array<number>;
    /**
     * Unit Ids
     */
    unit_ids: Array<string>;
};

/**
 * DescriptionStatus
 *
 * Outcome of describing an image with the vision model.
 */
export type DescriptionStatus = 'described' | 'skipped' | 'not_described';

/**
 * DocumentBody
 *
 * A document of the library with its newest job.
 *
 * Attributes:
 * id: Document id.
 * file_name: Name of the uploaded file.
 * size_bytes: Size of the file.
 * page_count: Page count, unknown for encrypted files.
 * created_at: Time the document was registered.
 * latest_job: Newest job, or ``None`` until its job is enqueued.
 */
export type DocumentBody = {
    /**
     * Id
     */
    id: string;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Created At
     */
    created_at: string;
    latest_job: JobBody | null;
};

/**
 * DocumentPageBody
 *
 * One page of documents, newest first.
 *
 * Attributes:
 * items: Documents of this page.
 * next_cursor: Cursor of the next page, or ``None`` on the last page.
 */
export type DocumentPageBody = {
    /**
     * Items
     */
    items: Array<DocumentBody>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * ElementBody
 *
 * A captured element with its position and relationships.
 *
 * Attributes:
 * id: Element id.
 * kind: Type of content.
 * page: 1-based page number.
 * bbox: Position on the page.
 * reading_order: Order within the document.
 * heading_level: Level of a heading.
 * text: Text content, or the Markdown of a table.
 * table: Rows and columns of a table.
 * origin: Whether the text came from the text layer or from recognition.
 * confidence: Recognition confidence of recognized text.
 * image_url: Relative URL of the stored crop of an image.
 * image_class: Classifier label of an image.
 * labels: Text printed inside an image.
 * description: Generated description of an image.
 * description_status: Outcome of describing an image.
 * unverified_identifiers: Identifiers of the description absent from the
 * image's labels and caption.
 * is_decorative: Whether the image is a logo or a repeated decoration.
 * relationships: Every link that touches the element.
 */
export type ElementBody = {
    /**
     * Id
     */
    id: string;
    kind: ElementKind;
    /**
     * Page
     */
    page: number;
    bbox: BoundingBoxBody;
    /**
     * Reading Order
     */
    reading_order: number;
    /**
     * Heading Level
     */
    heading_level: number | null;
    /**
     * Text
     */
    text: string | null;
    table: TableBody | null;
    origin: TextOrigin;
    /**
     * Confidence
     */
    confidence: number | null;
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Image Class
     */
    image_class: string | null;
    /**
     * Labels
     */
    labels: Array<string>;
    /**
     * Description
     */
    description: string | null;
    description_status: DescriptionStatus | null;
    /**
     * Unverified Identifiers
     */
    unverified_identifiers: Array<string>;
    /**
     * Is Decorative
     */
    is_decorative: boolean;
    /**
     * Relationships
     */
    relationships: Array<RelationshipBody>;
};

/**
 * ElementKind
 *
 * Type of an extracted element.
 */
export type ElementKind = 'heading' | 'paragraph' | 'list_item' | 'caption' | 'table' | 'image' | 'page_furniture';

/**
 * ElementPageBody
 *
 * One page of elements in reading order.
 *
 * Attributes:
 * items: Elements of this page.
 * next_cursor: Cursor of the next page, or ``None`` on the last page.
 */
export type ElementPageBody = {
    /**
     * Items
     */
    items: Array<ElementBody>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * FailureCode
 *
 * Machine-readable cause of a failed job.
 */
export type FailureCode = 'encrypted_document' | 'corrupt_document' | 'no_extractable_text' | 'provider_unavailable' | 'interrupted_repeatedly' | 'internal_error';

/**
 * JobBody
 *
 * State and progress of an ingestion job.
 *
 * Built from a domain job with ``model_validate(job)``, which reads only the
 * declared fields, so lease and worker details never reach clients.
 *
 * Attributes:
 * id: Job id.
 * document_id: Document being ingested.
 * status: Lifecycle state.
 * stage: Current step while processing.
 * attempt: Attempts started so far.
 * max_attempts: Attempts allowed.
 * pages_done: Pages processed in the current attempt.
 * pages_total: Pages to process, once known.
 * failure_code: Cause of a failure.
 * failure_reason: Human-readable failure reason.
 * summary: Counts of a completed job.
 * created_at: Creation time.
 * started_at: Time of the first claim.
 * finished_at: Time the job completed or failed.
 */
export type JobBody = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    status: JobStatus;
    stage: JobStage | null;
    /**
     * Attempt
     */
    attempt: number;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Pages Done
     */
    pages_done: number;
    /**
     * Pages Total
     */
    pages_total: number | null;
    failure_code: FailureCode | null;
    /**
     * Failure Reason
     */
    failure_reason: string | null;
    summary: JobSummaryBody | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * JobStage
 *
 * Step a processing job is currently running.
 */
export type JobStage = 'extracting' | 'describing_figures' | 'building_units' | 'embedding' | 'indexing' | 'finalizing';

/**
 * JobStatus
 *
 * Lifecycle state of an ingestion job.
 */
export type JobStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * JobSummaryBody
 *
 * Counts of what a completed job captured.
 *
 * Attributes:
 * pages: Pages processed.
 * text_elements: Headings, paragraphs, list items and captions.
 * tables: Table elements.
 * table_chains: Tables that continue across pages.
 * images: Image elements.
 * figures_described: Images with a generated description.
 * figures_skipped: Images not sent to the vision model.
 * figures_not_described: Images whose description failed.
 * retrieval_units: Units written to the index.
 * recognized_pages: Pages that went through text recognition.
 */
export type JobSummaryBody = {
    /**
     * Pages
     */
    pages: number;
    /**
     * Text Elements
     */
    text_elements: number;
    /**
     * Tables
     */
    tables: number;
    /**
     * Table Chains
     */
    table_chains: number;
    /**
     * Images
     */
    images: number;
    /**
     * Figures Described
     */
    figures_described: number;
    /**
     * Figures Skipped
     */
    figures_skipped: number;
    /**
     * Figures Not Described
     */
    figures_not_described: number;
    /**
     * Retrieval Units
     */
    retrieval_units: number;
    /**
     * Recognized Pages
     */
    recognized_pages: number;
};

/**
 * NotEnoughReason
 *
 * Why a question received no answer.
 */
export type NotEnoughReason = 'no_searchable_documents' | 'no_relevant_content' | 'not_answered_by_sources' | 'no_valid_citations';

/**
 * Problem
 *
 * RFC 9457 problem details, the body of every error response.
 *
 * Attributes:
 * type: Always ``about:blank``, so ``title`` is the phrase of the status.
 * title: Standard phrase of the HTTP status.
 * status: HTTP status code.
 * detail: Explanation of this occurrence, sent for client errors only.
 * instance: Path of the request.
 * code: Stable machine-readable code in lowercase snake case.
 * request_id: Correlation id of the request.
 */
export type Problem = {
    /**
     * Type
     */
    type?: 'about:blank';
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: number;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Instance
     */
    instance: string;
    /**
     * Code
     */
    code: string;
    /**
     * Request Id
     */
    request_id: string;
};

/**
 * QuestionBody
 *
 * A question about the ingested documents.
 *
 * The length of the question is not limited here: the use case enforces the
 * configurable limit and answers ``invalid_question``.
 *
 * Attributes:
 * question: The question, in any language.
 */
export type QuestionBody = {
    /**
     * Question
     */
    question: string;
};

/**
 * RelationshipBody
 *
 * A directed link between two elements.
 *
 * Attributes:
 * source_id: Element the link starts from, such as a caption.
 * target_id: Element the link points to, such as an image.
 * kind: Meaning of the link.
 */
export type RelationshipBody = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Target Id
     */
    target_id: string;
    kind: RelationshipKind;
};

/**
 * RelationshipKind
 *
 * Kind of link between two extracted elements.
 */
export type RelationshipKind = 'caption_of' | 'title_of' | 'describes' | 'near' | 'continues';

/**
 * SourceBody
 *
 * A retrieval unit supplied to the answer model.
 *
 * Attributes:
 * unit_id: Retrieval unit id.
 * rank: Position in the fused ranking.
 * similarity: Dense cosine similarity to the question.
 * document_id: Document of the unit.
 * document_name: File name of that document.
 * section: Heading path, outermost first.
 * pages: Pages the unit spans.
 * content_type: Text, table or figure unit.
 * excerpt: Beginning of the unit text.
 * cited: Whether the answer cites the unit.
 * citation_number: Citation that cites the unit.
 * low_confidence_text: Part of the content was recognized with low confidence.
 * generated_description: The content includes a figure description written by
 * a model.
 * unverified_identifiers: Identifiers of that description missing from the
 * figure's labels and caption.
 * tables: Rows of each part of a table unit.
 * figure_ids: Non-decorative image elements associated with the unit.
 */
export type SourceBody = {
    /**
     * Unit Id
     */
    unit_id: string;
    /**
     * Rank
     */
    rank: number;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Document Name
     */
    document_name: string;
    /**
     * Section
     */
    section: Array<string>;
    /**
     * Pages
     */
    pages: Array<number>;
    content_type: UnitType;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Cited
     */
    cited: boolean;
    /**
     * Citation Number
     */
    citation_number: number | null;
    /**
     * Low Confidence Text
     */
    low_confidence_text: boolean;
    /**
     * Generated Description
     */
    generated_description: boolean;
    /**
     * Unverified Identifiers
     */
    unverified_identifiers: Array<string>;
    /**
     * Tables
     */
    tables: Array<TableContentBody>;
    /**
     * Figure Ids
     */
    figure_ids: Array<string>;
};

/**
 * TableBody
 *
 * Rows and columns of a table.
 *
 * Attributes:
 * rows: Number of rows, the header included.
 * columns: Number of columns.
 * cells: Cell text, row by row.
 */
export type TableBody = {
    /**
     * Rows
     */
    rows: number;
    /**
     * Columns
     */
    columns: number;
    /**
     * Cells
     */
    cells: Array<Array<string>>;
};

/**
 * TableContentBody
 *
 * Rows of one part of a table.
 *
 * Attributes:
 * page: Page of this part.
 * rows: Cell text, header row first.
 */
export type TableContentBody = {
    /**
     * Page
     */
    page: number;
    /**
     * Rows
     */
    rows: Array<Array<string>>;
};

/**
 * TextOrigin
 *
 * Where the text of an element came from.
 */
export type TextOrigin = 'text_layer' | 'recognized';

/**
 * UnitType
 *
 * Type of a retrieval unit.
 */
export type UnitType = 'text' | 'table' | 'figure';

/**
 * UploadAccepted
 *
 * Identifiers returned by an upload.
 *
 * Attributes:
 * document_id: Document registered for the file's content.
 * job_id: Job that ingests the document.
 * status: Current state of that job.
 * already_ingested: Whether identical content had already completed.
 */
export type UploadAccepted = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Job Id
     */
    job_id: string;
    status: JobStatus;
    /**
     * Already Ingested
     */
    already_ingested: boolean;
};

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessResponses = {
    /**
     * Response Liveness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessErrors = {
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/documents';
};

export type ListDocumentsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentPageBody;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    headers?: {
        'X-Request-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/documents';
};

export type UploadDocumentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Content Too Large
     */
    413: Problem;
    /**
     * Unsupported Media Type
     */
    415: Problem;
    /**
     * Unprocessable Content
     */
    422: Problem;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Identical content already ingested
     */
    200: UploadAccepted;
    /**
     * Job pending or processing
     */
    202: UploadAccepted;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobBody;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type DeleteDocumentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type GetDocumentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentBody;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type ListDocumentElementsData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number | null;
        /**
         * Kind
         */
        kind?: ElementKind | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/documents/{document_id}/elements';
};

export type ListDocumentElementsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
};

export type ListDocumentElementsError = ListDocumentElementsErrors[keyof ListDocumentElementsErrors];

export type ListDocumentElementsResponses = {
    /**
     * Successful Response
     */
    200: ElementPageBody;
};

export type ListDocumentElementsResponse = ListDocumentElementsResponses[keyof ListDocumentElementsResponses];

export type GetDocumentImageData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Element Id
         */
        element_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/images/{element_id}';
};

export type GetDocumentImageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type GetDocumentImageError = GetDocumentImageErrors[keyof GetDocumentImageErrors];

export type GetDocumentImageResponses = {
    /**
     * PNG image
     */
    200: Blob | File;
};

export type GetDocumentImageResponse = GetDocumentImageResponses[keyof GetDocumentImageResponses];

export type GetDocumentPageImageData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Page Number
         */
        page_number: number;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/pages/{page_number}/image';
};

export type GetDocumentPageImageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
};

export type GetDocumentPageImageError = GetDocumentPageImageErrors[keyof GetDocumentPageImageErrors];

export type GetDocumentPageImageResponses = {
    /**
     * PNG image
     */
    200: Blob | File;
};

export type GetDocumentPageImageResponse = GetDocumentPageImageResponses[keyof GetDocumentPageImageResponses];

export type AskQuestionData = {
    body: QuestionBody;
    headers?: {
        'X-Request-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/questions';
};

export type AskQuestionErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
    /**
     * Gateway Timeout
     */
    504: Problem;
};

export type AskQuestionError = AskQuestionErrors[keyof AskQuestionErrors];

export type AskQuestionResponses = {
    /**
     * Successful Response
     */
    200: AnswerBody;
};

export type AskQuestionResponse = AskQuestionResponses[keyof AskQuestionResponses];
