// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AnswerStatus
 *
 * Whether the documents supported an answer.
 */
export const zAnswerStatus = z.enum(['answered', 'not_enough_information']);

/**
 * Body_uploadDocument
 */
export const zBodyUploadDocument = z.object({
    file: z.string()
});

/**
 * BoundingBoxBody
 *
 * Position on a page in PDF points with a top-left origin.
 *
 * Attributes:
 * left: Distance from the left edge of the page.
 * top: Distance from the top edge of the page.
 * right: Distance from the left edge to the right side of the box.
 * bottom: Distance from the top edge to the bottom side of the box.
 * origin: Always ``top_left``.
 */
export const zBoundingBoxBody = z.object({
    left: z.number(),
    top: z.number(),
    right: z.number(),
    bottom: z.number(),
    origin: z.literal('top_left').optional().default('top_left')
});

/**
 * AnswerImageBody
 *
 * A figure returned with an answer.
 *
 * Attributes:
 * element_id: Image element id.
 * document_id: Document of the figure.
 * document_name: File name of that document.
 * page: Page of the figure.
 * bbox: Position of the figure on the page.
 * caption: Caption of the figure, if any.
 * unit_id: Cited unit that brought the figure.
 * url: Path of the PNG, served by the document image route.
 */
export const zAnswerImageBody = z.object({
    element_id: z.uuid(),
    document_id: z.uuid(),
    document_name: z.string(),
    page: z.int(),
    bbox: zBoundingBoxBody,
    caption: z.string().nullable(),
    unit_id: z.uuid(),
    url: z.string()
});

/**
 * CitationBody
 *
 * A numbered citation of the answer.
 *
 * Attributes:
 * number: Number of the ``[n]`` markers that refer to it.
 * document_id: Cited document.
 * document_name: File name of the cited document.
 * pages: Cited pages, ascending.
 * unit_ids: Retrieval units behind the citation.
 */
export const zCitationBody = z.object({
    number: z.int(),
    document_id: z.uuid(),
    document_name: z.string(),
    pages: z.array(z.int()),
    unit_ids: z.array(z.uuid())
});

/**
 * DescriptionStatus
 *
 * Outcome of describing an image with the vision model.
 */
export const zDescriptionStatus = z.enum([
    'described',
    'skipped',
    'not_described'
]);

/**
 * ElementKind
 *
 * Type of an extracted element.
 */
export const zElementKind = z.enum([
    'heading',
    'paragraph',
    'list_item',
    'caption',
    'table',
    'image',
    'page_furniture'
]);

/**
 * FailureCode
 *
 * Machine-readable cause of a failed job.
 */
export const zFailureCode = z.enum([
    'encrypted_document',
    'corrupt_document',
    'no_extractable_text',
    'provider_unavailable',
    'interrupted_repeatedly',
    'internal_error'
]);

/**
 * JobStage
 *
 * Step a processing job is currently running.
 */
export const zJobStage = z.enum([
    'extracting',
    'describing_figures',
    'building_units',
    'embedding',
    'indexing',
    'finalizing'
]);

/**
 * JobStatus
 *
 * Lifecycle state of an ingestion job.
 */
export const zJobStatus = z.enum([
    'pending',
    'processing',
    'completed',
    'failed'
]);

/**
 * JobSummaryBody
 *
 * Counts of what a completed job captured.
 *
 * Attributes:
 * pages: Pages processed.
 * text_elements: Headings, paragraphs, list items and captions.
 * tables: Table elements.
 * table_chains: Tables that continue across pages.
 * images: Image elements.
 * figures_described: Images with a generated description.
 * figures_skipped: Images not sent to the vision model.
 * figures_not_described: Images whose description failed.
 * retrieval_units: Units written to the index.
 * recognized_pages: Pages that went through text recognition.
 */
export const zJobSummaryBody = z.object({
    pages: z.int(),
    text_elements: z.int(),
    tables: z.int(),
    table_chains: z.int(),
    images: z.int(),
    figures_described: z.int(),
    figures_skipped: z.int(),
    figures_not_described: z.int(),
    retrieval_units: z.int(),
    recognized_pages: z.int()
});

/**
 * JobBody
 *
 * State and progress of an ingestion job.
 *
 * Built from a domain job with ``model_validate(job)``, which reads only the
 * declared fields, so lease and worker details never reach clients.
 *
 * Attributes:
 * id: Job id.
 * document_id: Document being ingested.
 * status: Lifecycle state.
 * stage: Current step while processing.
 * attempt: Attempts started so far.
 * max_attempts: Attempts allowed.
 * pages_done: Pages processed in the current attempt.
 * pages_total: Pages to process, once known.
 * failure_code: Cause of a failure.
 * failure_reason: Human-readable failure reason.
 * summary: Counts of a completed job.
 * created_at: Creation time.
 * started_at: Time of the first claim.
 * finished_at: Time the job completed or failed.
 */
export const zJobBody = z.object({
    id: z.uuid(),
    document_id: z.uuid(),
    status: zJobStatus,
    stage: zJobStage.nullable(),
    attempt: z.int(),
    max_attempts: z.int(),
    pages_done: z.int(),
    pages_total: z.int().nullable(),
    failure_code: zFailureCode.nullable(),
    failure_reason: z.string().nullable(),
    summary: zJobSummaryBody.nullable(),
    created_at: z.iso.datetime(),
    started_at: z.iso.datetime().nullable(),
    finished_at: z.iso.datetime().nullable()
});

/**
 * DocumentBody
 *
 * A document of the library with its newest job.
 *
 * Attributes:
 * id: Document id.
 * file_name: Name of the uploaded file.
 * size_bytes: Size of the file.
 * page_count: Page count, unknown for encrypted files.
 * created_at: Time the document was registered.
 * latest_job: Newest job, or ``None`` until its job is enqueued.
 */
export const zDocumentBody = z.object({
    id: z.uuid(),
    file_name: z.string(),
    size_bytes: z.int(),
    page_count: z.int().nullable(),
    created_at: z.iso.datetime(),
    latest_job: zJobBody.nullable()
});

/**
 * DocumentPageBody
 *
 * One page of documents, newest first.
 *
 * Attributes:
 * items: Documents of this page.
 * next_cursor: Cursor of the next page, or ``None`` on the last page.
 */
export const zDocumentPageBody = z.object({
    items: z.array(zDocumentBody),
    next_cursor: z.string().nullable()
});

/**
 * NotEnoughReason
 *
 * Why a question received no answer.
 */
export const zNotEnoughReason = z.enum([
    'no_searchable_documents',
    'no_relevant_content',
    'not_answered_by_sources',
    'no_valid_citations'
]);

/**
 * Problem
 *
 * RFC 9457 problem details, the body of every error response.
 *
 * Attributes:
 * type: Always ``about:blank``, so ``title`` is the phrase of the status.
 * title: Standard phrase of the HTTP status.
 * status: HTTP status code.
 * detail: Explanation of this occurrence, sent for client errors only.
 * instance: Path of the request.
 * code: Stable machine-readable code in lowercase snake case.
 * request_id: Correlation id of the request.
 */
export const zProblem = z.object({
    type: z.literal('about:blank').optional().default('about:blank'),
    title: z.string(),
    status: z.int(),
    detail: z.string().nullish(),
    instance: z.string(),
    code: z.string().regex(/^[a-z][a-z0-9_]*$/),
    request_id: z.string()
});

/**
 * QuestionBody
 *
 * A question about the ingested documents.
 *
 * The length of the question is not limited here: the use case enforces the
 * configurable limit and answers ``invalid_question``.
 *
 * Attributes:
 * question: The question, in any language.
 */
export const zQuestionBody = z.object({
    question: z.string()
});

/**
 * RelationshipKind
 *
 * Kind of link between two extracted elements.
 */
export const zRelationshipKind = z.enum([
    'caption_of',
    'title_of',
    'describes',
    'near',
    'continues'
]);

/**
 * RelationshipBody
 *
 * A directed link between two elements.
 *
 * Attributes:
 * source_id: Element the link starts from, such as a caption.
 * target_id: Element the link points to, such as an image.
 * kind: Meaning of the link.
 */
export const zRelationshipBody = z.object({
    source_id: z.uuid(),
    target_id: z.uuid(),
    kind: zRelationshipKind
});

/**
 * TableBody
 *
 * Rows and columns of a table.
 *
 * Attributes:
 * rows: Number of rows, the header included.
 * columns: Number of columns.
 * cells: Cell text, row by row.
 */
export const zTableBody = z.object({
    rows: z.int(),
    columns: z.int(),
    cells: z.array(z.array(z.string()))
});

/**
 * TableContentBody
 *
 * Rows of one part of a table.
 *
 * Attributes:
 * page: Page of this part.
 * rows: Cell text, header row first.
 */
export const zTableContentBody = z.object({
    page: z.int(),
    rows: z.array(z.array(z.string()))
});

/**
 * TextOrigin
 *
 * Where the text of an element came from.
 */
export const zTextOrigin = z.enum(['text_layer', 'recognized']);

/**
 * ElementBody
 *
 * A captured element with its position and relationships.
 *
 * Attributes:
 * id: Element id.
 * kind: Type of content.
 * page: 1-based page number.
 * bbox: Position on the page.
 * reading_order: Order within the document.
 * heading_level: Level of a heading.
 * text: Text content, or the Markdown of a table.
 * table: Rows and columns of a table.
 * origin: Whether the text came from the text layer or from recognition.
 * confidence: Recognition confidence of recognized text.
 * image_url: Relative URL of the stored crop of an image.
 * image_class: Classifier label of an image.
 * labels: Text printed inside an image.
 * description: Generated description of an image.
 * description_status: Outcome of describing an image.
 * unverified_identifiers: Identifiers of the description absent from the
 * image's labels and caption.
 * is_decorative: Whether the image is a logo or a repeated decoration.
 * relationships: Every link that touches the element.
 */
export const zElementBody = z.object({
    id: z.uuid(),
    kind: zElementKind,
    page: z.int(),
    bbox: zBoundingBoxBody,
    reading_order: z.int(),
    heading_level: z.int().nullable(),
    text: z.string().nullable(),
    table: zTableBody.nullable(),
    origin: zTextOrigin,
    confidence: z.number().nullable(),
    image_url: z.string().nullable(),
    image_class: z.string().nullable(),
    labels: z.array(z.string()),
    description: z.string().nullable(),
    description_status: zDescriptionStatus.nullable(),
    unverified_identifiers: z.array(z.string()),
    is_decorative: z.boolean(),
    relationships: z.array(zRelationshipBody)
});

/**
 * ElementPageBody
 *
 * One page of elements in reading order.
 *
 * Attributes:
 * items: Elements of this page.
 * next_cursor: Cursor of the next page, or ``None`` on the last page.
 */
export const zElementPageBody = z.object({
    items: z.array(zElementBody),
    next_cursor: z.string().nullable()
});

/**
 * UnitType
 *
 * Type of a retrieval unit.
 */
export const zUnitType = z.enum([
    'text',
    'table',
    'figure'
]);

/**
 * SourceBody
 *
 * A retrieval unit supplied to the answer model.
 *
 * Attributes:
 * unit_id: Retrieval unit id.
 * rank: Position in the fused ranking.
 * similarity: Dense cosine similarity to the question.
 * document_id: Document of the unit.
 * document_name: File name of that document.
 * section: Heading path, outermost first.
 * pages: Pages the unit spans.
 * content_type: Text, table or figure unit.
 * excerpt: Beginning of the unit text.
 * cited: Whether the answer cites the unit.
 * citation_number: Citation that cites the unit.
 * low_confidence_text: Part of the content was recognized with low confidence.
 * generated_description: The content includes a figure description written by
 * a model.
 * unverified_identifiers: Identifiers of that description missing from the
 * figure's labels and caption.
 * tables: Rows of each part of a table unit.
 * figure_ids: Non-decorative image elements associated with the unit.
 */
export const zSourceBody = z.object({
    unit_id: z.uuid(),
    rank: z.int(),
    similarity: z.number(),
    document_id: z.uuid(),
    document_name: z.string(),
    section: z.array(z.string()),
    pages: z.array(z.int()),
    content_type: zUnitType,
    excerpt: z.string(),
    cited: z.boolean(),
    citation_number: z.int().nullable(),
    low_confidence_text: z.boolean(),
    generated_description: z.boolean(),
    unverified_identifiers: z.array(z.string()),
    tables: z.array(zTableContentBody),
    figure_ids: z.array(z.uuid())
});

/**
 * AnswerBody
 *
 * The answer to a question.
 *
 * Attributes:
 * status: ``answered`` or ``not_enough_information``.
 * reason: Why there is no answer, only when not answered.
 * answer: Markdown with ``[n]`` markers, or the not-enough message.
 * not_covered: What the documents do not answer, for a partial answer.
 * citations: Numbered citations.
 * sources: Every unit supplied to the answer model, in rank order.
 * primary_image: The figure closest to the most relevant cited text.
 * related_images: Other figures of the cited units.
 */
export const zAnswerBody = z.object({
    status: zAnswerStatus,
    reason: zNotEnoughReason.nullable(),
    answer: z.string(),
    not_covered: z.string().nullable(),
    citations: z.array(zCitationBody),
    sources: z.array(zSourceBody),
    primary_image: zAnswerImageBody.nullable(),
    related_images: z.array(zAnswerImageBody)
});

/**
 * UploadAccepted
 *
 * Identifiers returned by an upload.
 *
 * Attributes:
 * document_id: Document registered for the file's content.
 * job_id: Job that ingests the document.
 * status: Current state of that job.
 * already_ingested: Whether identical content had already completed.
 */
export const zUploadAccepted = z.object({
    document_id: z.uuid(),
    job_id: z.uuid(),
    status: zJobStatus,
    already_ingested: z.boolean()
});

/**
 * Response Liveness
 *
 * Successful Response
 */
export const zLivenessResponse = z.record(z.string(), z.string());

export const zListDocumentsQuery = z.object({
    limit: z.int().gte(1).lte(200).optional().default(50),
    cursor: z.string().nullish()
});

/**
 * Successful Response
 */
export const zListDocumentsResponse = zDocumentPageBody;

export const zUploadDocumentBody = zBodyUploadDocument;

export const zUploadDocumentHeaders = z.object({
    'X-Request-ID': z.string().max(128).optional()
});

/**
 * Identical content already ingested
 */
export const zUploadDocumentResponse = zUploadAccepted;

export const zGetJobPath = z.object({
    job_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetJobResponse = zJobBody;

export const zGetDocumentPath = z.object({
    document_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetDocumentResponse = zDocumentBody;

export const zListDocumentElementsPath = z.object({
    document_id: z.uuid()
});

export const zListDocumentElementsQuery = z.object({
    page: z.int().gte(1).nullish(),
    kind: zElementKind.nullish(),
    limit: z.int().gte(1).lte(200).optional().default(50),
    cursor: z.string().nullish()
});

/**
 * Successful Response
 */
export const zListDocumentElementsResponse = zElementPageBody;

export const zGetDocumentImagePath = z.object({
    document_id: z.uuid(),
    element_id: z.uuid()
});

/**
 * PNG image
 */
export const zGetDocumentImageResponse = z.string();

export const zGetDocumentPageImagePath = z.object({
    document_id: z.uuid(),
    page_number: z.int().gte(1)
});

/**
 * PNG image
 */
export const zGetDocumentPageImageResponse = z.string();

export const zAskQuestionBody = zQuestionBody;

export const zAskQuestionHeaders = z.object({
    'X-Request-ID': z.string().max(128).optional()
});

/**
 * Successful Response
 */
export const zAskQuestionResponse = zAnswerBody;
